# Generated by Django 2.0.4 on 2018-04-29 07:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_fsm
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcrDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_url', models.URLField()),
                ('callback_url', models.URLField(blank=True)),
                ('priority', models.IntegerField(default=10)),
                ('state', django_fsm.FSMField(default='created', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OCR Document',
                'verbose_name_plural': 'OCR Documents',
            },
        ),
        migrations.CreateModel(
            name='OcrResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scanned_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('state', django_fsm.FSMField(default='created', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ocr_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ocr.OcrDocument')),
            ],
            options={
                'verbose_name': 'OCR Result',
                'verbose_name_plural': 'OCR Results',
            },
        ),
    ]
